# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: networking/v1alpha3/yx_adapter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from policy.v1beta1 import cfg_pb2 as policy_dot_v1beta1_dot_cfg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='networking/v1alpha3/yx_adapter.proto',
  package='networking.v1alpha3',
  syntax='proto3',
  serialized_options=_b('Z istio.io/api/networking/v1alpha3'),
  serialized_pb=_b('\n$networking/v1alpha3/yx_adapter.proto\x12\x13networking.v1alpha3\x1a\x18policy/v1beta1/cfg.proto\"-\n\x0bKafkaConfig\x12\x0f\n\x07\x62rokers\x18\x01 \x03(\t\x12\r\n\x05topic\x18\x02 \x01(\t\"\x84\x01\n\tYXAdapter\x12?\n\x0esample_percent\x18\x01 \x01(\x0b\x32\'.istio.policy.v1beta1.FractionalPercent\x12\x36\n\x0ckafka_tracer\x18\x02 \x01(\x0b\x32 .networking.v1alpha3.KafkaConfigB\"Z istio.io/api/networking/v1alpha3b\x06proto3')
  ,
  dependencies=[policy_dot_v1beta1_dot_cfg__pb2.DESCRIPTOR,])




_KAFKACONFIG = _descriptor.Descriptor(
  name='KafkaConfig',
  full_name='networking.v1alpha3.KafkaConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='brokers', full_name='networking.v1alpha3.KafkaConfig.brokers', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic', full_name='networking.v1alpha3.KafkaConfig.topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=132,
)


_YXADAPTER = _descriptor.Descriptor(
  name='YXAdapter',
  full_name='networking.v1alpha3.YXAdapter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_percent', full_name='networking.v1alpha3.YXAdapter.sample_percent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kafka_tracer', full_name='networking.v1alpha3.YXAdapter.kafka_tracer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=267,
)

_YXADAPTER.fields_by_name['sample_percent'].message_type = policy_dot_v1beta1_dot_cfg__pb2._FRACTIONALPERCENT
_YXADAPTER.fields_by_name['kafka_tracer'].message_type = _KAFKACONFIG
DESCRIPTOR.message_types_by_name['KafkaConfig'] = _KAFKACONFIG
DESCRIPTOR.message_types_by_name['YXAdapter'] = _YXADAPTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KafkaConfig = _reflection.GeneratedProtocolMessageType('KafkaConfig', (_message.Message,), {
  'DESCRIPTOR' : _KAFKACONFIG,
  '__module__' : 'networking.v1alpha3.yx_adapter_pb2'
  # @@protoc_insertion_point(class_scope:networking.v1alpha3.KafkaConfig)
  })
_sym_db.RegisterMessage(KafkaConfig)

YXAdapter = _reflection.GeneratedProtocolMessageType('YXAdapter', (_message.Message,), {
  'DESCRIPTOR' : _YXADAPTER,
  '__module__' : 'networking.v1alpha3.yx_adapter_pb2'
  # @@protoc_insertion_point(class_scope:networking.v1alpha3.YXAdapter)
  })
_sym_db.RegisterMessage(YXAdapter)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
