// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: networking/v1alpha3/yx_adapter.proto

package v1alpha3

import (
	bytes "bytes"
	fmt "fmt"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	_ "istio.io/api/policy/v1beta1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for KafkaConfig
func (this *KafkaConfig) MarshalJSON() ([]byte, error) {
	str, err := YxAdapterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for KafkaConfig
func (this *KafkaConfig) UnmarshalJSON(b []byte) error {
	return YxAdapterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for YXAdapter
func (this *YXAdapter) MarshalJSON() ([]byte, error) {
	str, err := YxAdapterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for YXAdapter
func (this *YXAdapter) UnmarshalJSON(b []byte) error {
	return YxAdapterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	YxAdapterMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	YxAdapterUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
